// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/protobuf/InternalRequest.proto

package ca.NetSysLab.ProtocolBuffers;

public final class InternalRequest {
  private InternalRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EpidemicRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EpidemicRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes epId = 1;</code>
     */
    boolean hasEpId();
    /**
     * <code>required bytes epId = 1;</code>
     */
    com.google.protobuf.ByteString getEpId();

    /**
     * <code>required .EpidemicRequest.EpidemicType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .EpidemicRequest.EpidemicType type = 2;</code>
     */
    ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType getType();

    /**
     * <code>optional string server = 3;</code>
     */
    boolean hasServer();
    /**
     * <code>optional string server = 3;</code>
     */
    java.lang.String getServer();
    /**
     * <code>optional string server = 3;</code>
     */
    com.google.protobuf.ByteString
        getServerBytes();

    /**
     * <code>optional int32 port = 4;</code>
     */
    boolean hasPort();
    /**
     * <code>optional int32 port = 4;</code>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code EpidemicRequest}
   */
  public  static final class EpidemicRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EpidemicRequest)
      EpidemicRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EpidemicRequest.newBuilder() to construct.
    private EpidemicRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EpidemicRequest() {
      epId_ = com.google.protobuf.ByteString.EMPTY;
      type_ = 0;
      server_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EpidemicRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              epId_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType value = ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              server_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_EpidemicRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_EpidemicRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.class, ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code EpidemicRequest.EpidemicType}
     */
    public enum EpidemicType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEAD = 0;</code>
       */
      DEAD(0),
      /**
       * <code>ALIVE = 1;</code>
       */
      ALIVE(1),
      ;

      /**
       * <code>DEAD = 0;</code>
       */
      public static final int DEAD_VALUE = 0;
      /**
       * <code>ALIVE = 1;</code>
       */
      public static final int ALIVE_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EpidemicType valueOf(int value) {
        return forNumber(value);
      }

      public static EpidemicType forNumber(int value) {
        switch (value) {
          case 0: return DEAD;
          case 1: return ALIVE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EpidemicType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EpidemicType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EpidemicType>() {
              public EpidemicType findValueByNumber(int number) {
                return EpidemicType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final EpidemicType[] VALUES = values();

      public static EpidemicType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EpidemicType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:EpidemicRequest.EpidemicType)
    }

    private int bitField0_;
    public static final int EPID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString epId_;
    /**
     * <code>required bytes epId = 1;</code>
     */
    public boolean hasEpId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes epId = 1;</code>
     */
    public com.google.protobuf.ByteString getEpId() {
      return epId_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required .EpidemicRequest.EpidemicType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .EpidemicRequest.EpidemicType type = 2;</code>
     */
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType getType() {
      @SuppressWarnings("deprecation")
      ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType result = ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType.valueOf(type_);
      return result == null ? ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType.DEAD : result;
    }

    public static final int SERVER_FIELD_NUMBER = 3;
    private volatile java.lang.Object server_;
    /**
     * <code>optional string server = 3;</code>
     */
    public boolean hasServer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string server = 3;</code>
     */
    public java.lang.String getServer() {
      java.lang.Object ref = server_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          server_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string server = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServerBytes() {
      java.lang.Object ref = server_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        server_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <code>optional int32 port = 4;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 port = 4;</code>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEpId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, epId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, server_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, epId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, server_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest other = (ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest) obj;

      boolean result = true;
      result = result && (hasEpId() == other.hasEpId());
      if (hasEpId()) {
        result = result && getEpId()
            .equals(other.getEpId());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasServer() == other.hasServer());
      if (hasServer()) {
        result = result && getServer()
            .equals(other.getServer());
      }
      result = result && (hasPort() == other.hasPort());
      if (hasPort()) {
        result = result && (getPort()
            == other.getPort());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEpId()) {
        hash = (37 * hash) + EPID_FIELD_NUMBER;
        hash = (53 * hash) + getEpId().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasServer()) {
        hash = (37 * hash) + SERVER_FIELD_NUMBER;
        hash = (53 * hash) + getServer().hashCode();
      }
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EpidemicRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EpidemicRequest)
        ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_EpidemicRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_EpidemicRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.class, ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        epId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        server_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_EpidemicRequest_descriptor;
      }

      public ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.getDefaultInstance();
      }

      public ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest build() {
        ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest buildPartial() {
        ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest result = new ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.epId_ = epId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.server_ = server_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest other) {
        if (other == ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.getDefaultInstance()) return this;
        if (other.hasEpId()) {
          setEpId(other.getEpId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasServer()) {
          bitField0_ |= 0x00000004;
          server_ = other.server_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasEpId()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString epId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes epId = 1;</code>
       */
      public boolean hasEpId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes epId = 1;</code>
       */
      public com.google.protobuf.ByteString getEpId() {
        return epId_;
      }
      /**
       * <code>required bytes epId = 1;</code>
       */
      public Builder setEpId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        epId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes epId = 1;</code>
       */
      public Builder clearEpId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        epId_ = getDefaultInstance().getEpId();
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>required .EpidemicRequest.EpidemicType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .EpidemicRequest.EpidemicType type = 2;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType getType() {
        @SuppressWarnings("deprecation")
        ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType result = ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType.valueOf(type_);
        return result == null ? ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType.DEAD : result;
      }
      /**
       * <code>required .EpidemicRequest.EpidemicType type = 2;</code>
       */
      public Builder setType(ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest.EpidemicType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .EpidemicRequest.EpidemicType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object server_ = "";
      /**
       * <code>optional string server = 3;</code>
       */
      public boolean hasServer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string server = 3;</code>
       */
      public java.lang.String getServer() {
        java.lang.Object ref = server_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            server_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string server = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServerBytes() {
        java.lang.Object ref = server_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          server_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string server = 3;</code>
       */
      public Builder setServer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        server_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string server = 3;</code>
       */
      public Builder clearServer() {
        bitField0_ = (bitField0_ & ~0x00000004);
        server_ = getDefaultInstance().getServer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string server = 3;</code>
       */
      public Builder setServerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        server_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>optional int32 port = 4;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 port = 4;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional int32 port = 4;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000008;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 port = 4;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EpidemicRequest)
    }

    // @@protoc_insertion_point(class_scope:EpidemicRequest)
    private static final ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest();
    }

    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EpidemicRequest>
        PARSER = new com.google.protobuf.AbstractParser<EpidemicRequest>() {
      public EpidemicRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EpidemicRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EpidemicRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EpidemicRequest> getParserForType() {
      return PARSER;
    }

    public ca.NetSysLab.ProtocolBuffers.InternalRequest.EpidemicRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EpidemicRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EpidemicRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#main/protobuf/InternalRequest.proto\"\217\001" +
      "\n\017EpidemicRequest\022\014\n\004epId\030\001 \002(\014\022+\n\004type\030" +
      "\002 \002(\0162\035.EpidemicRequest.EpidemicType\022\016\n\006" +
      "server\030\003 \001(\t\022\014\n\004port\030\004 \001(\005\"#\n\014EpidemicTy" +
      "pe\022\010\n\004DEAD\020\000\022\t\n\005ALIVE\020\001B/\n\034ca.NetSysLab." +
      "ProtocolBuffersB\017InternalRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EpidemicRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EpidemicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EpidemicRequest_descriptor,
        new java.lang.String[] { "EpId", "Type", "Server", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
